### ISSUE TITLE
See if it would be possible to add specific requirements at will

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/edd-addon-tools#2]
I don't know if this would be possible, but it would be neat if we could figure out a way to set custom requirements and check them--not sure if the addon tool could loop through a series of `function_exists`, `class_exists` checks or something like that, but we have some extensions which have requirements other than WP/PHP/EDD, such as:
- The pushover notifications one
- MailPoet

Okay I'm currently blanking on a list but I guess I ran into this when I activated our MailPoet extension and couldn't figure it out (not familiar with MailPoet) and had to search our docs. It would be neat if we could somehow automatically include MailPoet in the list of requirements.

**Comment by ashleyfae** [comment]
Yeah I think that could be doable.

**Comment by ashleyfae** [comment]
Actually I believe it's already possible.
